#!/bin/sh
# Regenerate rtl/index.qip: every RTL file the core needs, in a stable order.
# Run from the repo root whenever a file is added or removed.
set -e
out=rtl/index.qip
{
echo "# =============================================================================="
echo "# Gaiapolis core RTL -- generated by tools/gen_qip.sh, do not edit"
echo "# =============================================================================="
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) ""]'
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) "data"]'
for f in $(cd rtl && ls *.sv | sort); do
    echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"$f\"]"
done
echo ""
echo "# TG68K.C 68000/68010/68020 kernel (LGPL, Tobias Gubener), GHDL-converted"
echo 'set_global_assignment -name VERILOG_FILE [file join $::quartus(qip_path) "../modules/cpu-tg68k/gen/tg68k.v"]'
echo "# tv80 Z80 (MIT, Guy Hutchison)"
for f in $(cd modules/cpu-tv80 && ls *.v | sort); do
    echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) \"../modules/cpu-tv80/$f\"]"
done
} > $out
echo "wrote $out ($(grep -c FILE $out) files)"
