#!/bin/sh
# Regenerate rtl/index.qip: every RTL file the core needs, in a stable order.
# Run from the repo root whenever a file is added or removed.
set -e
out=rtl/index.qip
{
echo "# =============================================================================="
echo "# Namco ND-1 core RTL -- generated by tools/gen_qip.sh, do not edit"
echo "# =============================================================================="
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) ""]'
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) "data"]'
for f in $(cd rtl && ls *.sv | sort); do
    echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"$f\"]"
done
echo ""
echo "# fx68k 68000 (Jorge Cwik, GPL-3.0)"
for f in fx68k.sv fx68kAlu.sv uaddrPla.sv; do
    echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"../modules/cpu-fx68k/$f\"]"
done
} > $out
echo "wrote $out ($(grep -c FILE $out) files)"
