#!/usr/bin/env python3
"""Turn a raw MAME region dump into a committable hash manifest.

tools/dump_regions.lua writes artifacts/mame_regions.txt, which contains actual
ROM bytes and therefore must never be committed or published. This reduces it
to SHA-256 digests of each slice, which verify a built image just as well and
carry no ROM content.

Usage: make_region_manifest.py [artifacts/mame_regions.txt] [docs/rom-regions.sha256]
"""
import sys, hashlib

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else 'artifacts/mame_regions.txt'
    dst = sys.argv[2] if len(sys.argv) > 2 else 'docs/rom-regions.sha256'
    lines = open(src).read().split('\n')
    out = ['# SHA-256 of slices of each MAME ROM region for ncv1, as loaded by',
           '# MAME 0.288. Generated by tools/make_region_manifest.py from a local',
           '# tools/dump_regions.lua dump. Contains no ROM data.',
           '# fields: region  offset  length  sha256']
    i = n = 0
    while i < len(lines):
        if lines[i].startswith('SLICE '):
            _, tag, off = lines[i].split()
            data = bytes.fromhex(lines[i + 1])
            out.append(f'{tag} {off} {len(data)} {hashlib.sha256(data).hexdigest()}')
            n += 1
            i += 2
        else:
            i += 1
    if not n:
        sys.exit(f'error: no slices found in {src}')
    open(dst, 'w').write('\n'.join(out) + '\n')
    print(f'wrote {dst}: {n} slices')

if __name__ == '__main__':
    main()
